import Footer from './components/Footer'
import './globals.css'


export const metadata = {
  title: 'MovieBox',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-Body'>
        {children}
      </body>
    </html>
  )
}
